overrides:
  "foo": &tenant_overrides
    ingestion_rate_mb: 100
    unordered_writes: true # DEPRECATED
    ruler_evaluation_delay_duration: 1m # DEPRECATED
    ruler_remote_write_headers: [ "foo", "bar" ] # DEPRECATED
    per_tenant_override_config: ./overrides.yaml # DEPRECATED
    per_tenant_override_period: 5s # DEPRECATED
    allow_deletes: true # DEPRECATED
  "bar": *tenant_overrides

multi_kv_config:
  primary: ""
  mirror_enabled: null
